apiVersion: apps/v1
kind: Deployment
metadata:
  name: ran
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ran
  replicas: 1
  template:
    metadata:
      labels:
        app: ran
    spec:
      initContainers:
        {{- include "ztxInitContainer" . | nindent 8 }}
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: ran
          image: "umakantk/ueransim:ztx_01"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: ["-c", "sleep infinity"]
          env:
            - name: PCS_SETUP_TUN_INTF
              value: "false"
