apiVersion: v1
name: ztx
version: 1.0.0
appVersion: 1.0.0
description: Helm chart for Purdue ZTX Security Service

type: application

keywords:
  - 5G
  - ZTX

maintainers:
  - name:  Purdue CS
    email: ukulkarn@purdue.edu